export const dataSalida1 = {
    id: 306427,
    anterior: 306355,
    boletos_save: false,
    cobrador: {
        id: 391,
        activo: true,
        castigado: false,
        boletos_save: true,
        codigo: '391',
        conductor: true,
        dni: '41078589',
        estado: 'R',
        nombre: 'RAMIREZ CHAVEZ  JOSE  ANTONIO',
        vencido: false,
        vigente: true,
        vencimiento: '2025-11-25'
    },
    conductor: {
        id: 391,
        activo: true,
        castigado: false,
        boletos_save: true,
        codigo: '391',
        conductor: true,
        dni: '41078589',
        estado: 'R',
        nombre: 'RAMIREZ CHAVEZ  JOSE  ANTONIO',
        vencido: false,
        vigente: true,
        vencimiento: '2025-11-25'
    },
    creado: '2023-08-23T09:32:38.313462-05:00',
    dia: '2023-08-23',
    estado: 'R',
    fin: null,
    frecuencia: 16,
    ingreso: '2023-08-23T09:30:16.960920-05:00',
    inicio: '2023-08-23T09:35:00.000000-05:00',
    lado: false,
    liquidacion: null,
    multa: 0,
    multa_creada: false,
    padron: 60,
    pasajeros: 0,
    pasajerosBoletos: 0,
    pasajerosTickets: 0,
    placa: 'C9A765',
    produccion: 0,
    produccionBoletos: 0,
    produccionDiferencia: 0,
    produccionTickets: 0,
    produccionTransbordo: 0,
    record: 0,
    ruta: {
        id: 1,
        codigo: '9306',
        plantilla_actual: 1
    },
    siguiente: null,
    tickets_save: false,
    unidad: {
        id: 35,
        activo: true,
        actual: 306427,
        arreglada: 671,
        aval: {
            id: 51,
            cargo: 'PROPIETARIO',
            nombre: 'LAZARO ORE PRUDENCIO',
            username: 'PRUDENCIOL'
        },
        baja: null,
        bloqueado: false,
        bloqueado_a: false,
        bloqueado_b: false,
        boletos_save: true,
        cobrador: {
            id: 391,
            activo: true,
            castigado: false,
            boletos_save: true,
            codigo: '391',
            conductor: true,
            dni: '41078589',
            estado: 'R',
            nombre: 'RAMIREZ CHAVEZ  JOSE  ANTONIO',
            vencido: false,
            vigente: true,
            vencimiento: '2025-11-25'
        },
        cola: true,
        conductor: {
            id: 391,
            activo: true,
            castigado: false,
            boletos_save: true,
            codigo: '391',
            conductor: true,
            dni: '41078589',
            estado: 'R',
            nombre: 'RAMIREZ CHAVEZ  JOSE  ANTONIO',
            vencido: false,
            vigente: true,
            vencimiento: '2025-11-25'
        },
        estado: 'R',
        estadoDetail: 'En Ruta',
        fin_viaje: '2023-08-23T09:30:13.000000-05:00',
        ingreso: null,
        ingreso_espera: '2023-08-23T09:30:16.960920-05:00',
        lado: false,
        logueado: null,
        monitoreo: {
            id: 51,
            cargo: 'PROPIETARIO',
            nombre: 'LAZARO ORE PRUDENCIO',
            username: 'PRUDENCIOL'
        },
        observacion: '23:11 >',
        odometro: 0,
        orden: 1,
        padron: {
            id: 60,
            activo: true,
            paquete: null,
            propietario: 65
        },
        placa: 'C9A765',
        prioridad: 'R',
        propietario: {
            id: 51,
            cargo: 'PROPIETARIO',
            nombre: 'LAZARO ORE PRUDENCIO',
            username: 'PRUDENCIOL'
        },
        record: 671,
        ruta: {
            id: 1,
            codigo: '9306',
            plantilla_actual: 1
        },
        vencido: false,
        vigente: true,
        vencimiento: '2023-09-10',
        alto: 0.0,
        ancho: 0.0,
        largo: 0.0,
        peso: 0.0,
        carga: 0.0,
        asientos: 0,
        pasajeros: 0,
        fabricacion: 0,
        carroceria: '',
        color: '',
        modelo: 'IVECO',
        marca: '',
        clase: '',
        cilindros: 0,
        motor: '',
        numser: '',
        modalidad: '',
        poliza: '',
        tarjeta: '',
        prioridadDetail: 'Ruta',
        suministros: [
            {
                id: 193659,
                actual: 194498,
                boleto: {
                    id: 8,
                    alerta: 100,
                    minimo: 50,
                    nombre: 'DIRECTO',
                    opcional: 70,
                    orden: 1,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 5.0
                },
                cantidad: 103,
                estado: 'En Uso',
                fin: 194601,
                hora: '2023-08-03T15:11:36.246592-05:00',
                inicio: 194401,
                serie: 'J01.',
                stock: 699,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            },
            {
                id: 189527,
                actual: 208134,
                boleto: {
                    id: 1,
                    alerta: 100,
                    minimo: 50,
                    nombre: 'DIRECTO',
                    opcional: 70,
                    orden: 2,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 4.0
                },
                cantidad: 67,
                estado: 'En Uso',
                fin: 208201,
                hora: '2023-07-16T19:38:51.222541-05:00',
                inicio: 208001,
                serie: 'G01',
                stock: 187,
                terminado: false,
                usuario: {
                    id: 311,
                    cargo: 'DESPACHADOR - CAJERO',
                    nombre: 'JORGE LUIS FLORES QUISPE',
                    username: 'JORGEL'
                }
            },
            {
                id: 193770,
                actual: 129193,
                boleto: {
                    id: 2,
                    alerta: 100,
                    minimo: 50,
                    nombre: 'INTERURBANO',
                    opcional: 70,
                    orden: 3,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 3.0
                },
                cantidad: 8,
                estado: 'En Uso',
                fin: 129201,
                hora: '2023-08-04T06:41:16.665125-05:00',
                inicio: 129001,
                serie: 'J01',
                stock: 801,
                terminado: false,
                usuario: {
                    id: 311,
                    cargo: 'DESPACHADOR - CAJERO',
                    nombre: 'JORGE LUIS FLORES QUISPE',
                    username: 'JORGEL'
                }
            },
            {
                id: 198215,
                actual: 141201,
                boleto: {
                    id: 2,
                    alerta: 100,
                    minimo: 50,
                    nombre: 'INTERURBANO',
                    opcional: 70,
                    orden: 3,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 3.0
                },
                cantidad: 200,
                estado: 'Reserva',
                fin: 141401,
                hora: '2023-08-22T07:14:32.436390-05:00',
                inicio: 141201,
                serie: 'J01',
                stock: 801,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            },
            {
                id: 196843,
                actual: 198929,
                boleto: {
                    id: 3,
                    alerta: 100,
                    minimo: 50,
                    nombre: 'URBANO',
                    opcional: 90,
                    orden: 4,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 2.5
                },
                cantidad: 72,
                estado: 'En Uso',
                fin: 199001,
                hora: '2023-08-16T18:38:47.035658-05:00',
                inicio: 198801,
                serie: 'S01',
                stock: 751,
                terminado: false,
                usuario: {
                    id: 311,
                    cargo: 'DESPACHADOR - CAJERO',
                    nombre: 'JORGE LUIS FLORES QUISPE',
                    username: 'JORGEL'
                }
            },
            {
                id: 197442,
                actual: 256594,
                boleto: {
                    id: 14,
                    alerta: 100,
                    minimo: 100,
                    nombre: 'MED/UNIV/INTER',
                    opcional: 130,
                    orden: 5,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 2.0
                },
                cantidad: 7,
                estado: 'En Uso',
                fin: 256601,
                hora: '2023-08-19T06:19:07.844477-05:00',
                inicio: 256401,
                serie: 'F01',
                stock: 859,
                terminado: false,
                usuario: {
                    id: 17,
                    cargo: 'DESPACHADOR',
                    nombre: 'LUIS ROSALES RAMOS',
                    username: 'lrosales'
                }
            },
            {
                id: 198310,
                actual: 280201,
                boleto: {
                    id: 14,
                    alerta: 100,
                    minimo: 100,
                    nombre: 'MED/UNIV/INTER',
                    opcional: 130,
                    orden: 5,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 2.0
                },
                cantidad: 200,
                estado: 'Reserva',
                fin: 280401,
                hora: '2023-08-22T14:06:05.503054-05:00',
                inicio: 280201,
                serie: 'F01',
                stock: 859,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            },
            {
                id: 198216,
                actual: 895459,
                boleto: {
                    id: 10,
                    alerta: 100,
                    minimo: 120,
                    nombre: 'MED/UNIV/URB',
                    opcional: 300,
                    orden: 6,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 1.5
                },
                cantidad: 142,
                estado: 'En Uso',
                fin: 895601,
                hora: '2023-08-22T07:14:32.439823-05:00',
                inicio: 895401,
                serie: 'F01',
                stock: 855,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            },
            {
                id: 198393,
                actual: 903401,
                boleto: {
                    id: 10,
                    alerta: 100,
                    minimo: 120,
                    nombre: 'MED/UNIV/URB',
                    opcional: 300,
                    orden: 6,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 1.5
                },
                cantidad: 200,
                estado: 'Reserva',
                fin: 903601,
                hora: '2023-08-22T21:12:22.963325-05:00',
                inicio: 903401,
                serie: 'F01',
                stock: 856,
                terminado: false,
                usuario: {
                    id: 165,
                    cargo: 'GRIFERA MARISCAL',
                    nombre: 'ELSIN JHACKELINE VASQUEZ GUTIERREZ',
                    username: 'JEVASQUEZ'
                }
            },
            {
                id: 198311,
                actual: 110693,
                boleto: {
                    id: 9,
                    alerta: 100,
                    minimo: 190,
                    nombre: 'PROM/ESCOLAR',
                    opcional: 300,
                    orden: 7,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 1.0
                },
                cantidad: 108,
                estado: 'En Uso',
                fin: 110801,
                hora: '2023-08-22T14:06:05.510700-05:00',
                inicio: 110601,
                serie: 'R08',
                stock: 862,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            },
            {
                id: 198505,
                actual: 132801,
                boleto: {
                    id: 9,
                    alerta: 100,
                    minimo: 190,
                    nombre: 'PROM/ESCOLAR',
                    opcional: 300,
                    orden: 7,
                    reintegro: false,
                    ruta: 1,
                    tarifa: 1.0
                },
                cantidad: 200,
                estado: 'Reserva',
                fin: 133001,
                hora: '2023-08-23T09:32:36.419833-05:00',
                inicio: 132801,
                serie: 'R08',
                stock: 862,
                terminado: false,
                usuario: {
                    id: 16,
                    cargo: 'DESPACHADOR',
                    nombre: 'AMADO OLIVEROS CARRILLO',
                    username: 'AMADOO'
                }
            }
        ]
    },
    vuelta: 2,
    boletaje: [],
    controles: [
        {
            id: 5972806,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 1,
            grabado: null,
            hora: '2023-08-23T09:38:00.000000-05:00',
            multa: 0,
            orden: 1,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 3,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972807,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 28,
            grabado: null,
            hora: '2023-08-23T09:43:00.000000-05:00',
            multa: 0,
            orden: 2,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972808,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 2,
            grabado: null,
            hora: '2023-08-23T09:48:00.000000-05:00',
            multa: 1,
            orden: 3,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972809,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 29,
            grabado: null,
            hora: '2023-08-23T09:53:00.000000-05:00',
            multa: 0,
            orden: 4,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972810,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 3,
            grabado: null,
            hora: '2023-08-23T09:58:00.000000-05:00',
            multa: 1,
            orden: 5,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972811,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 43,
            grabado: null,
            hora: '2023-08-23T10:01:00.000000-05:00',
            multa: 0,
            orden: 6,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 3,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972812,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 30,
            grabado: null,
            hora: '2023-08-23T10:05:00.000000-05:00',
            multa: 0,
            orden: 7,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 4,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972813,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 4,
            grabado: null,
            hora: '2023-08-23T10:10:00.000000-05:00',
            multa: 0,
            orden: 8,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972814,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 44,
            grabado: null,
            hora: '2023-08-23T10:13:00.000000-05:00',
            multa: 0,
            orden: 9,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 3,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972815,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 31,
            grabado: null,
            hora: '2023-08-23T10:19:00.000000-05:00',
            multa: 0,
            orden: 10,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 6,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972816,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 32,
            grabado: null,
            hora: '2023-08-23T10:24:00.000000-05:00',
            multa: 0,
            orden: 11,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972817,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 5,
            grabado: null,
            hora: '2023-08-23T10:26:00.000000-05:00',
            multa: 0,
            orden: 12,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 2,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972818,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 6,
            grabado: null,
            hora: '2023-08-23T10:35:00.000000-05:00',
            multa: 0,
            orden: 13,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 9,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972819,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 7,
            grabado: null,
            hora: '2023-08-23T10:43:00.000000-05:00',
            multa: 0,
            orden: 14,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 8,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972820,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 33,
            grabado: null,
            hora: '2023-08-23T10:49:00.000000-05:00',
            multa: 0,
            orden: 15,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 6,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972821,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 34,
            grabado: null,
            hora: '2023-08-23T11:00:00.000000-05:00',
            multa: 0,
            orden: 16,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 11,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972822,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 35,
            grabado: null,
            hora: '2023-08-23T11:09:00.000000-05:00',
            multa: 0,
            orden: 17,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 9,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972823,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 8,
            grabado: null,
            hora: '2023-08-23T11:16:00.000000-05:00',
            multa: 0,
            orden: 18,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 7,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972824,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 36,
            grabado: null,
            hora: '2023-08-23T11:19:00.000000-05:00',
            multa: 0,
            orden: 19,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 3,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972825,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 9,
            grabado: null,
            hora: '2023-08-23T11:23:00.000000-05:00',
            multa: 0,
            orden: 20,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 4,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972826,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 37,
            grabado: null,
            hora: '2023-08-23T11:27:00.000000-05:00',
            multa: 0,
            orden: 21,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 4,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972827,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 38,
            grabado: null,
            hora: '2023-08-23T11:31:00.000000-05:00',
            multa: 0,
            orden: 22,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 4,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972828,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 10,
            grabado: null,
            hora: '2023-08-23T11:36:00.000000-05:00',
            multa: 0,
            orden: 23,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972829,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 11,
            grabado: null,
            hora: '2023-08-23T11:41:00.000000-05:00',
            multa: 0,
            orden: 24,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 5,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972830,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 12,
            grabado: null,
            hora: '2023-08-23T11:53:00.000000-05:00',
            multa: 0,
            orden: 25,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 12,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972831,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 13,
            grabado: null,
            hora: '2023-08-23T12:00:00.000000-05:00',
            multa: 0,
            orden: 26,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 7,
            volada: 0,
            record: 0,
            roundVolada: 0
        },
        {
            id: 5972832,
            atras: [],
            datero: [],
            estado: 'S',
            geocerca: 14,
            grabado: null,
            hora: '2023-08-23T12:07:00.000000-05:00',
            multa: 0,
            orden: 27,
            ponderado: 1,
            real: null,
            salida: 306427,
            tiempo: 7,
            volada: 0,
            record: 0,
            roundVolada: 0
        }
    ],
    inspecciones: [],
    tickets: []
}
