export const dataTicket4 = {
    id: 635849,
    abono: {
        id: 271778,
        abono: 78.0,
        anulado: false,
        caja: 8001,
        cliente: 112,
        detalle: 'Recibo P001-024809',
        dia: '2023-08-17',
        hora: '2023-08-17T09:35:06.457379-05:00',
        moneda: 1,
        usuario: 17
    },
    anulado: false,
    base: 0.0,
    caja: {
        id: 8001,
        contometro_final: null,
        contometro_inicial: null,
        fin: null,
        inicio: '2023-08-17T05:22:36.732053-05:00',
        lado: null,
        saldo_inicial: 0,
        sede: {
            id: 5,
            almacen: null,
            nombre: 'CAJA JICAMARCA',
            activo: true
        },
        transferencia: null,
        usuario: {
            id: 17,
            cargo: 'DESPACHADOR',
            nombre: 'LUIS ROSALES RAMOS',
            username: 'lrosales'
        }
    },
    cliente: {
        id: 112,
        activo: true,
        cliente_id: 83,
        codigo: 'ATB905',
        direccion: null,
        display_tipo: 'Unidad',
        distrito: '',
        dni: '08326276',
        email: null,
        nombre: 'FIGUEROA SANTA CRUZ, JULIO',
        padron: '78',
        persona: 'J',
        placa: 'ATB905',
        razon: '',
        referencia: '78',
        referencia_compuesta: 'P078 (ATB905)',
        ruc: null,
        telefono: null,
        tipo: 'U'
    },
    conductor: {
        id: 307,
        activo: true,
        castigado: false,
        boletos_save: true,
        codigo: 'ID5976',
        conductor: true,
        dni: '40561421',
        estado: 'T',
        nombre: 'QUISPE LLAVE RICARDO',
        vencido: false,
        vigente: true,
        vencimiento: '2024-01-02'
    },
    dia: '2023-08-17',
    deuda: null,
    deudas: [
        {
            id: 254527,
            dia: '2022-09-09',
            nombre: 'IMPUESTO VEHICULAR',
            inicial: 5319.01,
            saldo: 2629.01
        },
        {
            id: 399469,
            dia: '2023-03-16',
            nombre: 'SOAT TR 2023',
            inicial: 3792.05,
            saldo: 2572.05
        },
        {
            id: 427806,
            dia: '2022-09-23',
            nombre: 'FONDO DE MANT..TO',
            inicial: 100000.0,
            saldo: 96510.0
        }
    ],
    documento: {
        id: 12,
        activo: true,
        es_egreso: false,
        nombre: 'INTERNO',
        numero: 24842,
        sede: {
            id: 5,
            almacen: null,
            nombre: 'CAJA JICAMARCA',
            activo: true
        },
        serie: 'P001',
        sunat: {
            id: 1,
            codigo: 0,
            nombre: 'INTERNO',
            es_compra: true
        }
    },
    efectivo: true,
    fondos: [
        {
            id: 4,
            nombre: 'FONDO DE MANT..TO',
            total: 560.0
        },
        {
            id: 249,
            nombre: 'FONDO PAPELATAS 2023',
            total: 890.0
        }
    ],
    hora: '2023-08-17T09:35:06.372380-05:00',
    igv: 0.0,
    items: [
        {
            id: 1187305,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 254527,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 10.0,
                dia: '2022-09-09',
                en_reclamo: false,
                hora: '2022-09-08T22:49:10.662933-05:00',
                nombre: 'IMPUESTO VEHICULAR',
                precio: 5319.01,
                producto: 222,
                saldo: 2629.01
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 10.0,
            moneda: 1,
            observacion: '',
            pagado: 10.0,
            precio: 10.0,
            precio_unit: 10.0,
            producto: {
                id: 222,
                activo: true,
                automatico: false,
                cliente: 'U',
                codigo: '99',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'IMPUESTO VEHICULAR',
                precio: 0.0,
                servicio: true,
                stock: 0,
                variable: true
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187306,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 399469,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 10.0,
                dia: '2023-03-16',
                en_reclamo: false,
                hora: '2023-03-16T14:10:42.707188-05:00',
                nombre: 'SOAT TR 2023',
                precio: 3792.05,
                producto: 241,
                saldo: 2572.05
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 10.0,
            moneda: 1,
            observacion: '',
            pagado: 10.0,
            precio: 10.0,
            precio_unit: 10.0,
            producto: {
                id: 241,
                activo: true,
                automatico: false,
                cliente: 'U',
                codigo: '445',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'SOAT TR 2023',
                precio: 0.0,
                servicio: true,
                stock: 0,
                variable: true
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187307,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 427806,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 20.0,
                dia: '2022-09-23',
                en_reclamo: false,
                hora: '2022-09-22T17:37:24.493325-05:00',
                nombre: 'FONDO DE MANT..TO',
                precio: 100000.0,
                producto: 4,
                saldo: 96510.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 20.0,
            moneda: 1,
            observacion: '',
            pagado: 20.0,
            precio: 20.0,
            precio_unit: 20.0,
            producto: {
                id: 4,
                activo: true,
                automatico: false,
                cliente: 'U',
                codigo: '3',
                combustible: false,
                es_gasto: false,
                fondo: true,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'FONDO DE MANT..TO',
                precio: 0.0,
                servicio: true,
                stock: -1072000,
                variable: true
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187308,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 522010,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 0.0,
                dia: '2023-08-17',
                en_reclamo: false,
                hora: '2023-08-17T05:48:37.810809-05:00',
                nombre: 'BOLETAJE',
                precio: 8.0,
                producto: 8,
                saldo: 0.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 8.0,
            moneda: 1,
            observacion: '',
            pagado: 8.0,
            precio: 8.0,
            precio_unit: 8.0,
            producto: {
                id: 8,
                activo: true,
                automatico: true,
                cliente: 'U',
                codigo: '5',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'BOLETAJE',
                precio: 8.0,
                servicio: true,
                stock: -103000,
                variable: false
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187309,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 522012,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 0.0,
                dia: '2023-08-17',
                en_reclamo: false,
                hora: '2023-08-17T05:48:37.914163-05:00',
                nombre: 'COCH. CALLAO',
                precio: 10.0,
                producto: 31,
                saldo: 0.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 10.0,
            moneda: 1,
            observacion: '',
            pagado: 10.0,
            precio: 10.0,
            precio_unit: 10.0,
            producto: {
                id: 31,
                activo: true,
                automatico: true,
                cliente: 'U',
                codigo: '30',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'COCH. CALLAO',
                precio: 10.0,
                servicio: true,
                stock: 0,
                variable: false
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187310,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 522013,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 0.0,
                dia: '2023-08-17',
                en_reclamo: false,
                hora: '2023-08-17T05:48:37.960674-05:00',
                nombre: 'COCHERA JICAMARCA',
                precio: 3.0,
                producto: 12,
                saldo: 0.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 3.0,
            moneda: 1,
            observacion: '',
            pagado: 3.0,
            precio: 3.0,
            precio_unit: 3.0,
            producto: {
                id: 12,
                activo: true,
                automatico: true,
                cliente: 'U',
                codigo: '9',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'COCHERA JICAMARCA',
                precio: 3.0,
                servicio: true,
                stock: -103000,
                variable: false
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187311,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 522014,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 0.0,
                dia: '2023-08-17',
                en_reclamo: false,
                hora: '2023-08-17T05:48:38.010790-05:00',
                nombre: 'DESPACHO',
                precio: 2.0,
                producto: 10,
                saldo: 0.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 2.0,
            moneda: 1,
            observacion: '',
            pagado: 2.0,
            precio: 2.0,
            precio_unit: 2.0,
            producto: {
                id: 10,
                activo: true,
                automatico: true,
                cliente: 'U',
                codigo: '7',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'DESPACHO',
                precio: 2.0,
                servicio: true,
                stock: -103000,
                variable: false
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187312,
            base: 0.0,
            cantidad: 1.0,
            deuda: {
                id: 522019,
                anulado: false,
                cantidad: 1.0,
                cliente: 112,
                cuota: 0.0,
                dia: '2023-08-17',
                en_reclamo: false,
                hora: '2023-08-17T05:48:38.277325-05:00',
                nombre: 'PUNTOS DE CONTROL',
                precio: 5.0,
                producto: 55,
                saldo: 0.0
            },
            efectivo: true,
            igv: 0.0,
            inafecta: 5.0,
            moneda: 1,
            observacion: '',
            pagado: 5.0,
            precio: 5.0,
            precio_unit: 5.0,
            producto: {
                id: 55,
                activo: true,
                automatico: true,
                cliente: 'U',
                codigo: '101',
                combustible: false,
                es_gasto: false,
                fondo: false,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'PUNTOS DE CONTROL',
                precio: 5.0,
                servicio: true,
                stock: 0,
                variable: false
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        },
        {
            id: 1187313,
            base: 0.0,
            cantidad: 1.0,
            deuda: null,
            efectivo: true,
            igv: 0.0,
            inafecta: 10.0,
            moneda: 1,
            observacion: '',
            pagado: 10.0,
            precio: 10.0,
            precio_unit: 10.0,
            producto: {
                id: 249,
                activo: true,
                automatico: false,
                cliente: 'U',
                codigo: '503',
                combustible: false,
                es_gasto: false,
                fondo: true,
                fracciones: false,
                igv: null,
                isc: 0,
                moneda: 1,
                nombre: 'FONDO PAPELATAS 2023',
                precio: 10.0,
                servicio: true,
                stock: 0,
                variable: true
            },
            recibo: {
                id: 635849,
                anulado: false,
                dia: '2023-08-17',
                documento: 12,
                efectivo: true,
                hora: '2023-08-17T09:35:06.372380-05:00',
                moneda: 1,
                numero: '024809',
                pagado: true,
                saldo: 0.0,
                sended: null,
                serie: 'P001',
                total: 78.0,
                usuario: 17
            },
            saldo: 0.0,
            usuario: {
                id: 17,
                cargo: 'DESPACHADOR',
                nombre: 'LUIS ROSALES RAMOS',
                username: 'lrosales'
            }
        }
    ],
    inafecta: 78.0,
    modifica: null,
    moneda: {
        id: 1,
        nombre: 'Nuevo Sol',
        codigo: 'S/'
    },
    numero: '024809',
    observacion: null,
    pagado: true,
    saldo: 0.0,
    sended: null,
    serie: 'P001',
    ser_num: 'P001-024809',
    total: 78.0,
    usuario: 17
}
